from __future__ import annotations


SHORT_CONTEXT_REPEAT_COUNT = 3
COLLAPSED_SHORT_CONTEXT_MODE = "repeat3_collapsed_v1"
COLLAPSED_SHORT_CONTEXT_EFFECTIVE_REPEAT_COUNT = 1
LOCKED_NAME_ANCHOR_METRICS_VERSION = 2
