from __future__ import annotations


POSTPROCESS_PROFILE_NONE = "none"
POSTPROCESS_PROFILE_TEMPO = "ffmpeg_atempo_0_94_pcm_s16le_v1"
POSTPROCESS_ALGORITHM = "immutable_dual_decode_tempo_rescue_v1"
POSTPROCESS_PROFILES = (
    POSTPROCESS_PROFILE_NONE,
    POSTPROCESS_PROFILE_TEMPO,
)
POSTPROCESS_TEMPO_NUMERATOR = 94
POSTPROCESS_TEMPO_DENOMINATOR = 100
POSTPROCESS_TEMPO_FACTOR = POSTPROCESS_TEMPO_NUMERATOR / POSTPROCESS_TEMPO_DENOMINATOR
POSTPROCESS_SAMPLE_COUNT_RELATIVE_TOLERANCE = 0.01
POSTPROCESS_OUTPUT_CODEC = "pcm_s16le"

POSTPROCESS_PROFILE_FIELD = "postprocess_profile"
POSTPROCESS_SOURCE_CANDIDATE_ID_FIELD = "postprocess_source_candidate_id"
POSTPROCESS_SOURCE_SHA256_FIELD = "postprocess_source_sha256"
POSTPROCESS_SOURCE_SAMPLE_RATE_FIELD = "postprocess_source_sample_rate"
POSTPROCESS_SOURCE_SAMPLES_FIELD = "postprocess_source_samples"
POSTPROCESS_OUTPUT_SAMPLES_FIELD = "postprocess_output_samples"
POSTPROCESS_PROVENANCE_FIELDS = (
    POSTPROCESS_PROFILE_FIELD,
    POSTPROCESS_SOURCE_CANDIDATE_ID_FIELD,
    POSTPROCESS_SOURCE_SHA256_FIELD,
    POSTPROCESS_SOURCE_SAMPLE_RATE_FIELD,
    POSTPROCESS_SOURCE_SAMPLES_FIELD,
    POSTPROCESS_OUTPUT_SAMPLES_FIELD,
)
