from __future__ import annotations


HA_VOCALIZATION_DELIVERY_PROFILE = "ha_vocalization_v2"
HA_VOCALIZATION_MAX_TEMPERATURE = 0.55
HA_VOCALIZATION_MAX_TOP_P = 0.82
HA_VOCALIZATION_MAX_NEW_FRAMES = 23

HA_VOCALIZATION_PROFILE_FIELD = "tts_vocalization_delivery_profile"
HA_VOCALIZATION_TEMPERATURE_FIELD = "tts_sampling_temperature"
HA_VOCALIZATION_TOP_P_FIELD = "tts_sampling_top_p"
HA_VOCALIZATION_MAX_NEW_FRAMES_FIELD = "tts_vocalization_max_new_frames"
HA_VOCALIZATION_SAMPLE_RATE_FIELD = "vocalization_sample_rate"
HA_VOCALIZATION_ORIGINAL_SAMPLES_FIELD = "vocalization_original_samples"
HA_VOCALIZATION_TARGET_SAMPLES_FIELD = "vocalization_target_samples"
HA_VOCALIZATION_PADDING_SAMPLES_FIELD = "vocalization_padding_samples"
HA_VOCALIZATION_FINAL_SAMPLES_FIELD = "vocalization_final_samples"

HA_VOCALIZATION_SAMPLING_PROVENANCE_FIELDS = (
    HA_VOCALIZATION_PROFILE_FIELD,
    HA_VOCALIZATION_TEMPERATURE_FIELD,
    HA_VOCALIZATION_TOP_P_FIELD,
    HA_VOCALIZATION_MAX_NEW_FRAMES_FIELD,
)
HA_VOCALIZATION_PADDING_PROVENANCE_FIELDS = (
    HA_VOCALIZATION_SAMPLE_RATE_FIELD,
    HA_VOCALIZATION_ORIGINAL_SAMPLES_FIELD,
    HA_VOCALIZATION_TARGET_SAMPLES_FIELD,
    HA_VOCALIZATION_PADDING_SAMPLES_FIELD,
    HA_VOCALIZATION_FINAL_SAMPLES_FIELD,
)
HA_VOCALIZATION_PROVENANCE_FIELDS = (
    *HA_VOCALIZATION_SAMPLING_PROVENANCE_FIELDS,
    *HA_VOCALIZATION_PADDING_PROVENANCE_FIELDS,
)
